/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Community;
import static model.Community.communityDirectory;
import model.Doctor;
import static model.DoctorDirectory.doctorDirectory;
import model.Hospital;
import model.HospitalDirectory;
import static model.HospitalDirectory.hospitalDirectory;

/**
 *
 * @author jhalaksurve
 */
public class ManageHospitals extends javax.swing.JPanel {
    
    int flag = 0;

    HospitalDirectory hd ;//= new HospitalDirectory();
    /**
     * Creates new form ManageHospitals
     */
    public ManageHospitals() {
        initComponents();
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblState = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtHospitalName = new javax.swing.JTextField();
        lblCommunity = new javax.swing.JLabel();
        lblHospitalName = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        txtCommunity = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        lblCity = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHospital = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 204, 255));

        lblState.setFont(new java.awt.Font("Adelle Sans Devanagari", 0, 14)); // NOI18N
        lblState.setText("State");

        btnSearch.setBackground(new java.awt.Color(0, 153, 255));
        btnSearch.setFont(new java.awt.Font("Adelle Sans Devanagari", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblCommunity.setFont(new java.awt.Font("Adelle Sans Devanagari", 0, 14)); // NOI18N
        lblCommunity.setText("Community");

        lblHospitalName.setFont(new java.awt.Font("Adelle Sans Devanagari", 0, 14)); // NOI18N
        lblHospitalName.setText("Hospital Name");

        btnUpdate.setBackground(new java.awt.Color(0, 153, 255));
        btnUpdate.setFont(new java.awt.Font("Adelle Sans Devanagari", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 153, 255));
        btnDelete.setFont(new java.awt.Font("Adelle Sans Devanagari", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 153, 255));
        btnAdd.setFont(new java.awt.Font("Adelle Sans Devanagari", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblCity.setFont(new java.awt.Font("Adelle Sans Devanagari", 0, 14)); // NOI18N
        lblCity.setText("City");

        txtState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateActionPerformed(evt);
            }
        });

        tblHospital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Hospital Name", "Hospital Id", "Community", "City", "State"
            }
        ));
        tblHospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHospitalMouseClicked(evt);
            }
        });
        tblHospital.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblHospitalKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblHospital);

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnAdd))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHospitalName)
                                    .addComponent(lblState))
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(116, 116, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCommunity)
                                .addGap(77, 77, 77)
                                .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCommunity)
                    .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHospitalName))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblState)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnAdd)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:

       //int hospitalId = Integer.parseInt(txtHospitalId.getText());
        String hospitalName = txtHospitalName.getText();
        String community = txtCommunity.getText();
        String city = txtCity.getText();
        String state = txtState.getText();
        
        if(txtHospitalName.getText().isEmpty() || txtCommunity.getText().isEmpty() || txtCity.getText().isEmpty() || txtState.getText().isEmpty())
            JOptionPane.showMessageDialog(this,"Please enter all the details!!");
        else{ 
        for(Community c : communityDirectory){
        if(c.getCommunityName().equals(community)){
            flag = 1;
        }
        }
        if(flag == 1){
        hospitalDirectory.add(new Hospital( hospitalName, community, city, state));
        
        JOptionPane.showMessageDialog(this,"New Hospital added");

        populateTable();

        //txtHospitalId.setText("");
        txtHospitalName.setText("");
        txtCommunity.setText("");
        txtCity.setText("");
        txtState.setText("");
        }else JOptionPane.showMessageDialog(this,"Community doesn't exist");
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateActionPerformed

    private void tblHospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHospitalMouseClicked
        // TODO add your handling code here:
        
        int selectedRowIndex = tblHospital.getSelectedRow();
        if (selectedRowIndex<0){
        JOptionPane.showMessageDialog(this, "Select the row you want to DELETE");
        return;
        }
        DefaultTableModel model = (DefaultTableModel) tblHospital.getModel();
        Hospital selectedHospital;  
         selectedHospital= (Hospital) model.getValueAt(selectedRowIndex, 0);
         txtHospitalName.setText(selectedHospital.getHospitalName());
         //txtHospitalId.setText(String.valueOf(selectedHospital.getHospitalId()));
         txtCommunity.setText(selectedHospital.getHospitalCommunity());
         txtCity.setText(selectedHospital.getHospitalCity());
         txtState.setText(selectedHospital.getHospitalState());
         
    }//GEN-LAST:event_tblHospitalMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel tm;
        tm = (DefaultTableModel)tblHospital.getModel();
        if(tblHospital.getSelectedRowCount()==1){
           
     String name= txtHospitalName.getText();
//     int id = Integer.parseInt(txtHospitalId.getText());
     String community = txtCommunity.getText();
     String city = txtCity.getText();
     String state = txtState.getText();
     
     if(txtHospitalName.getText().isEmpty() || txtCommunity.getText().isEmpty() || txtCity.getText().isEmpty() || txtState.getText().isEmpty())
            JOptionPane.showMessageDialog(this,"Please enter all the details!!");
        else{ 
     
     tm.setValueAt(name, tblHospital.getSelectedRow(),0);
    // tm.setValueAt(id, tblHospital.getSelectedRow(),1);
     tm.setValueAt(community, tblHospital.getSelectedRow(),2);
     tm.setValueAt(city, tblHospital.getSelectedRow(),3);
     tm.setValueAt(state, tblHospital.getSelectedRow(),4);
     
     
     JOptionPane.showMessageDialog(this, "Updated Successfully");
     }
     //populateTable();
        }
        else{
            if(tblHospital.getRowCount() == 0){
                JOptionPane.showMessageDialog(this, "Table is empty!!");
            }
            else{
                JOptionPane.showMessageDialog(this, "Please select a single row.");
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblHospitalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblHospitalKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblHospitalKeyPressed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = tblHospital.getSelectedRow();
        
        if (selectedRowIndex < 0){
        
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblHospital.getModel();
        Hospital selectedDHospital = (Hospital)model.getValueAt(selectedRowIndex, 0);
        hd.deleteHospital(selectedDHospital);
        
        //txtHospitalId.setText("");
        txtHospitalName.setText("");
        txtCommunity.setText("");
        txtCity.setText("");
        txtState.setText("");
        
        
        JOptionPane.showMessageDialog(this, "Doctor Deleted.");
        
        populateTable();
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String query = txtSearch.getText();
        filter(query);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void filter(String query){
        DefaultTableModel model = (DefaultTableModel) tblHospital.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tblHospital.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));
    }
    
    private void populateTable(){
        
        /*PatientDirectory pd = new PatientDirectory();
        
        pd.addNewPatient("Shubhi Miradwal",1,"shubhi123",23,'F',"shubhimiradwal2304@gmail.com","Boston","O+");
        */

        DefaultTableModel model = (DefaultTableModel) tblHospital.getModel();
        model.setRowCount(0);
        
        for(Hospital h : hospitalDirectory){
        
            Object[] row = new Object[10];
            
            row[0] = h;
            row[1] = h.getHospitalId();
            row[2] = h.getHospitalCommunity();
            row[3] = h.getHospitalCity();
            row[4] = h.getHospitalState();
           
            
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblHospitalName;
    private javax.swing.JLabel lblState;
    private javax.swing.JTable tblHospital;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtHospitalName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtState;
    // End of variables declaration//GEN-END:variables
}
